### ISSUE TITLE
Consider Extensions as third part

### ISSUE THREAD

**Issue by nr458h** [FabianWilkens/snserver_ynh#2]
I'm very thankful for this app - do you consider also providing the extensions as an app?

Thanks anyway and have a good new year

**Comment by FabianWilkens** [comment]
I testet all the opensource extensions from StandardNotes. They are working with the selfhosted server and web app and mobile apps
But at the moment every user has to add each extensions manually.

I will try to figure something out.

**Comment by nr458h** [comment]
I saw your pull request for the extensions coming to the testing-branch
I'm very excited - so is there something I can do for you, to get it productiv?

Many thanks for your time!

**Comment by FabianWilkens** [comment]
Hi,

Sure if you want you can install it and test the new feature. ( See in the README at the bottom )

It's not ready but should work already.


At the moment only the site admin knows how to install the extensions. Instructions are sent via email.

But the users have to be informed after registration as well.

**Comment by nr458h** [comment]
Hi @FabianWilkens 
many thanks the update went through succesfully. But now I stuck while trying to get the extensions working for the clients. At the moment I have a running subscription for the extensions. So if you know maybe you can give me a hind
- how to remove a existing subscription for the official standard-extensions-service
- how to add the new selfhosted extensions to the clients
I also started already dicking into this problem - I'm just asking in case you know ;)

Many thanks and looking forward to have selfhosted extensions !!

**Comment by FabianWilkens** [comment]
If you make a new install, you have to choose if you want to install the extension on the server. You can change it later on the yunohost admin.

I saw that this is not clear in the email you get after upgradeing the yunohost app.

You can install/remove the extensions here:
https://your-domain.tld/yunohost/admin/#/apps/snserver/actions
And config the access domain.(Only required for the web app. Not for Desktop or mobile app.)
https://your-domain.tld/yunohost/admin/#/apps/snserver/config-panel

After that each user can install extentions from this link:
Example: https://snserver.your-domain.tld/extensions/

As I mentioned before the users get no information about this yet.


I am think that there should be a way to remove the extension repo you are using right now.

**Comment by nr458h** [comment]
Hi many thanks for the feedback.

I was looking for that pice of information ;)
`After that each user can install extentions from this link:
Example:  https://snserver.your-domain.tld/extensions/`

I found a way to remove the extension repo with this [guide ](https://standardnotes.org/help/41/my-extensions-appear-as-expired-even-though-my-subscription-is-still-valid) but now I'm facing a new problem
When I enter the URL (https://mysubdomain.nohost.me/snserver/extensions) here 
![image](https://user-images.githubusercontent.com/34851898/106318130-b2778000-626f-11eb-9d8d-8dd455eb03ac.png)
Than I'm unable to press install/or it does nothing
![image](https://user-images.githubusercontent.com/34851898/106318182-cd49f480-626f-11eb-9dd5-54d0dd15007e.png)

Probably this is related to my domain? I installed the server to mysubdomain.nohost.me/snserver and not to a dedicated subdomain.

Additionaly maybe you could change the button after performing an action in the .../actions panel

Kind regards

**Comment by FabianWilkens** [comment]
It is possible to install the server also on a path like you did.

But I think I know what the problem is.
Don't enter the extension url in Standard Notes.
Open it in you Browser.

This is not like the Standard Notes Extended Extensions Repo, where you install all extentions at once.

When you open the link you can install each extention you want. But one by one.

Unfortunately I found no way to install all these extentions at once yet.

I have to rewrite the email you get after installing or upgrading with better instructions. And also for the end users.


Waiting for any feedback you can give me.

**Comment by FabianWilkens** [comment]
I'm not sure what you mean by that:
> Additionaly maybe you could change the button after performing an action in the .../actions panel

**Comment by nr458h** [comment]
> I'm not sure what you mean by that:
>>Additionaly maybe you could change the button after performing an action in the .../actions panel
![image](https://user-images.githubusercontent.com/34851898/106337517-9edd1100-6291-11eb-959e-67258eaf735c.png)

**Comment by nr458h** [comment]
So well I figured out what to do **as a user** to get it up :) this was a long way ^^


1. If you use the standardnotes extension subscription, otherwise skip this step:remove the repo ([how to do that](https://standardnotes.org/help/41/my-extensions-appear-as-expired-even-though-my-subscription-is-still-valid))
2. Enter your extension-adress https://snserver.your-domain.tld/extensions/ in the fild where you can enter the extension code (all extensions previewsly installed should work now)
3. If you want to add additional extensions  
   - open your browser and go to https://snserver.your-domain.tld/extensions/
   - Copy the extension-link you want to add to your application
   - go back to your application and enter the link into the import-field

Thanks for your effort and your quick reply! At the moment everything works like expected

**Comment by FabianWilkens** [comment]
> 
> 
> > I'm not sure what you mean by that:
> > > Additionaly maybe you could change the button after performing an action in the .../actions panel
> > > ![image](https://user-images.githubusercontent.com/34851898/106337517-9edd1100-6291-11eb-959e-67258eaf735c.png)

Ahh ok.

Year i can't change that. It's part of yunohost

**Comment by FabianWilkens** [comment]
Pushed a few commits to testing.

Now there is also a selfhosted repo.

**Comment by nr458h** [comment]
I installed the extensions one week ago and everything works like a sharm!
Thank you very much!

**Comment by FabianWilkens** [comment]
Thanks.
Nice to hear that.

I'm simplifying everything right now.
Almost finished
